version: '3'
services:
  server:
    build: ../
    working_dir: /extension
    command: manage version
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    volumes:
      - $PWD:/extension
    environment:
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  redis:
    image: redis:3.0-alpine
    restart: unless-stopped
  postgres:
    image: postgres:9.5.6-alpine
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
